/*

 SAMAGYA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\GameboyDevelopment\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define samagyaWidth 40
#define samagyaHeight 18
#define samagyaBank 0

extern unsigned char samagya[];

/* End of SAMAGYA.H */
